// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtg6yJfPi2Lm5hMSFYeAHWAjHedqcfLNQ',
    appId: '1:920403951476:web:739bf9670ac546a6af3621',
    messagingSenderId: '920403951476',
    projectId: 'myproject-22b3c',
    authDomain: 'myproject-22b3c.firebaseapp.com',
    databaseURL: 'https://myproject-22b3c-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-22b3c.appspot.com',
    measurementId: 'G-9Q7LT4ZPMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBrUAAUlcejkFMhVLyJTRjQcM9EsSAJQ',
    appId: '1:920403951476:android:6a01a8c35d67c0d7af3621',
    messagingSenderId: '920403951476',
    projectId: 'myproject-22b3c',
    databaseURL: 'https://myproject-22b3c-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-22b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhHnMdNVVTH18s9E9hJGnw7q8VEtgR4A',
    appId: '1:920403951476:ios:540f8780d42f74ffaf3621',
    messagingSenderId: '920403951476',
    projectId: 'myproject-22b3c',
    databaseURL: 'https://myproject-22b3c-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-22b3c.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhHnMdNVVTH18s9E9hJGnw7q8VEtgR4A',
    appId: '1:920403951476:ios:540f8780d42f74ffaf3621',
    messagingSenderId: '920403951476',
    projectId: 'myproject-22b3c',
    databaseURL: 'https://myproject-22b3c-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-22b3c.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtg6yJfPi2Lm5hMSFYeAHWAjHedqcfLNQ',
    appId: '1:920403951476:web:ebb2c490658c1916af3621',
    messagingSenderId: '920403951476',
    projectId: 'myproject-22b3c',
    authDomain: 'myproject-22b3c.firebaseapp.com',
    databaseURL: 'https://myproject-22b3c-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-22b3c.appspot.com',
    measurementId: 'G-Z9HPYPP3M4',
  );
}
